baseURL = "https://perlweeklychallenge.org/"
languageCode = "en-us"
title = "Perl Weekly Challenge - for Perl5 & Perl6"
theme = "timer-hugo"
publishDir = "docs"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Team"
        url     = "/team"
        weight  = 3
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 4
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 5

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Airspace Hugo theme"
    author = "Themefisher"
    # Google Analitycs
    googleAnalitycsID = "Your ID"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "Perl Weekly Challenge"
        description = "You learn something valuable from all of the significant events and people, but you never touch your true potential until you challenge yourself to go beyond imposed limitations. - Roy T. Bennett"
        btn     = true
        btnText = "Explore ..."
        btnURL  = "/about"
        [[params.banner.flipText]]
            title   = "Challenger"
        [[params.banner.flipText]]
            title   = "Contributor"
        [[params.banner.flipText]]
            title   = "Motivator"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        content = "Hello, I’m a Perl 5 hacker with over 20 years of assoication. Since 2010, I have been contributing to CPAN. While doing so, I even adopted over 20 distributions. In the last 4 years, I have been religiously submitting Pull Request to the distributions hosted on GitHub. Last year, I joined the elite panel of editors of Perl Weekly newsletter under the guidance of Cheif Editor, Gabor Szabo. I have also written few articles for perl.com."
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "SO WHAT DO YOU THINK ?"
        content = "If you have any suggestions or ideas then please do share with us."
        btnText = "Contact with me"
        btnURL  = "/contact"

