baseURL = "https://perlweeklychallenge.org/"
languageCode = "en-us"
title = "Perl Weekly Challenge - Perl5 & Perl6"
theme = "timer-hugo"
publishDir = "docs"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Chart"
        url     = "/chart"
        weight  = 3
    [[menu.nav]]
        name    = "Team"
        url     = "/team"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 5
    [[menu.nav]]
        name    = "FAQ"
        url     = "/faq"
        weight  = 6
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 7

# Site Params
[params]
    home = "Home"
    logo = "images/logo.svg"
    dateFormat = "25 March 2019"
    # Meta data
    description = "Perl Weekly Challenge"
    author = "Perl Weekly Challenge Team"
    # Google Analitycs
    googleAnalitycsID = "UA-136524905-1"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "Perl Weekly Challenge"
        description = "You learn something valuable from all of the significant events and people, but you never touch your true potential until you challenge yourself to go beyond imposed limitations. - Roy T. Bennett"
        btn     = true
        btnText = "Challenge of the week"
        btnURL  = "/blog/perl-weekly-challenge-004"
        [[params.banner.flipText]]
            title   = "Champion"
        [[params.banner.flipText]]
            title   = "Contributor"
        [[params.banner.flipText]]
            title   = "Mentor"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        content = "Hello, I’m a Perl 5 hacker with over 20 years of association with Perl 5. Since 2010, I have been contributing to CPAN. While doing so, I have even adopted over 20 distributions. In the last 4 years, I have been religiously submitting Pull Request to the distributions hosted on GitHub. Last year, I joined the panel of editors of \"Perl Weekly\" newsletter under the guidance of Chief Editor, Gabor Szabo. I also sometimes write for \"perl.com\". I am one of the organisers of the London Perl Workshop. I have been giving talk at various Perl Conferences."
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "SO WHAT DO YOU THINK ?"
        content = "If you have any suggestions or ideas then please do share with us."
        btnText = "Contact with me"
        btnURL  = "/contact"

